version: 1.2
workflows:
   - name: TotalSegmentator_GPU
     subclass: WDL
     primaryDescriptorPath: /Terra/TotalSegmentator/GPU/v7.wdl
   - name: TotalSegmentatorSplitWorkflow
     subclass: WDL
     primaryDescriptorPath: /Terra/TotalSegmentator/splitWorkflow/splitWorkflow.wdl
     testParameterFiles:
     -  /sampleManifests/batch_1.csv
   - name: TotalSegmentatorSplitWorkflowV2
     subclass: WDL
     primaryDescriptorPath: /Terra/TotalSegmentator/splitWorkflow/splitWorkflowV2.wdl
     testParameterFiles:
     -  /sampleManifests/batch_1.csv
   - name: TotalSegmentatorCWLWorkflow
     subclass: CWL
     primaryDescriptorPath: /SevenBridges/TotalSegmentator/splitWorkflow/splitWorkflowV2.cwl
     testParameterFiles:
     -  /sampleManifests/batch_1.csv
          
    
