version: 1.2
workflows:
   - name: TotalSegmentator_GPU
     subclass: WDL
     primaryDescriptorPath: /Terra/TotalSegmentator/GPU/v7.wdl
   - name: TotalSegmentatorSplitWorkflow
     subclass: WDL
     primaryDescriptorPath: /Terra/TotalSegmentator/splitWorkflow/splitWorkflow.wdl
   - name: TotalSegmentatorSplitWorkflowV2
     subclass: WDL
     primaryDescriptorPath: /Terra/TotalSegmentator/splitWorkflow/splitWorkflowV2.wdl     
     
    
