version: 1.2
workflows:
   - name: TotalSegmentatortwoVmWorkflowOnTerra
     subclass: WDL
     primaryDescriptorPath: /workflows/TotalSegmentator/Terra/splitWorkflow/twoVM.wdl
     authors:
      - name: ImagingDataCommons
        email: vthiriveedhi@mgb.org  
   - name: TotalSegmentatorthreeVmWorkflowOnTerra
     subclass: WDL
     primaryDescriptorPath: /workflows/TotalSegmentator/Terra/splitWorkflow/threeVM.wdl
     authors:
      - name: ImagingDataCommons
        email: vthiriveedhi@mgb.org 
   - name: TotalSegmentatorOneVmWorkflowOnTerra
     subclass: WDL
     primaryDescriptorPath: /workflows/TotalSegmentator/Terra/splitWorkflow/oneVM.wdl
     authors:
      - name: ImagingDataCommons
        email: vthiriveedhi@mgb.org      
   - name: perFrameFunctionalGroupSequenceExtractionOnTerra
     subclass: WDL
     primaryDescriptorPath: /workflows/TotalSegmentator/Terra/postProcessing/perFrame.wdl   
     authors:
      - name: ImagingDataCommons
        email: vthiriveedhi@mgb.org
   - name: convertRadiomicsJsonToDataframeOnTerra
     subclass: WDL
     primaryDescriptorPath: /workflows/TotalSegmentator/Terra/postProcessing/convertRadiomicsJsonToDataframe.wdl   
     authors:
      - name: ImagingDataCommons
        email: vthiriveedhi@mgb.org           
   - name: TotalSegmentatortwoVmWorkflowOnSB-CGC
     subclass: CWL
     primaryDescriptorPath: /workflows/TotalSegmentator/SevenBridges/splitWorkflow/twoVM.cwl
     authors:
      - name: ImagingDataCommons
        email: vthiriveedhi@mgb.org    
   - name: TotalSegmentatorthreeVmWorkflowOnSB-CGC
     subclass: CWL
     primaryDescriptorPath: /workflows/TotalSegmentator/SevenBridges/splitWorkflow/threeVM.cwl
     authors:
      - name: ImagingDataCommons
        email: vthiriveedhi@mgb.org
   - name: TotalSegmentatorOneVmWorkflowOnSB-CGC
     subclass: CWL
     primaryDescriptorPath: /workflows/TotalSegmentator/SevenBridges/splitWorkflow/oneVM.cwl
     authors:
      - name: ImagingDataCommons
        email: vthiriveedhi@mgb.org