version: 1.2
workflows:
   - name: TotalSegmentatortwoVmWorkflowOnTerra
     subclass: WDL
     primaryDescriptorPath: /Terra/TotalSegmentator/splitWorkflow/twoVM.wdl
     testParameterFiles:
     -  /sampleManifests/batch_1.csv
   - name: TotalSegmentatorthreeVmWorkflowOnTerra
     subclass: WDL
     primaryDescriptorPath: /Terra/TotalSegmentator/splitWorkflow/threeVM.wdl
     testParameterFiles:
     -  /sampleManifests/batch_1.csv 
   - name: TotalSegmentatorOneVmWorkflowOnTerra
     subclass: WDL
     primaryDescriptorPath: /Terra/TotalSegmentator/splitWorkflow/oneVM.wdl
     testParameterFiles:
     -  /sampleManifests/batch_1.csv       
   - name: TotalSegmentatortwoVmWorkflowOnSB-CGC
     subclass: CWL
     primaryDescriptorPath: /SevenBridges/TotalSegmentator/splitWorkflow/twoVM.cwl
     testParameterFiles:
     -  /sampleManifests/batch_1.csv
   - name: TotalSegmentatorthreeVmWorkflowOnSB-CGC
     subclass: CWL
     primaryDescriptorPath: /SevenBridges/TotalSegmentator/splitWorkflow/threeVM.cwl
     testParameterFiles:
     -  /sampleManifests/batch_1.csv
 tools:
   - name: TotalSegmentatorOneVmWorkflowOnSB-CGC
     subclass: CWL
     primaryDescriptorPath: /Terra/TotalSegmentator/splitWorkflow/one.cwl
     testParameterFiles:
     -  /sampleManifests/batch_1.csv         
    
