name: download_convert_inference_totalseg

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfiles/TotalSegmentator/splitWorkflow/tasks1and2/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfiles/TotalSegmentator/splitWorkflow/tasks1and2/**'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Get Git Commit Hash
        id: git-commit-hash
        run: echo "::set-output name=commit_hash::$(git rev-parse HEAD)"
      
      - name: Copy additional files to build context
        run: |
          cp Dockerfiles/TotalSegmentator/splitWorkflow/tasks1and2/weights_download.sh .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfiles/TotalSegmentator/splitWorkflow/tasks1and2/Dockerfile
          push: true
          tags: vamsithiriveedhi/totalsegmentator:download_convert_inference_totalseg
          build-args: |
            GIT_HASH=${{ steps.git-commit-hash.outputs.commit_hash }}
