name: per_frame_functional_group_sequence

on:
  push:
    branches:
      - main  
    paths:
      - 'Dockerfiles/per_frame_functional_group_sequence/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Get Git Commit Hash
        id: git-commit-hash
        run: echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfiles/per_frame_functional_group_sequence/Dockerfile
          push: true
          tags: imagingdatacommons/per_frame_functional_group_sequence
          build-args: |
            GIT_HASH=${{ steps.git-commit-hash.outputs.commit_hash }}
